name: ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-type-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Banned tools check (storybook/tailwind)
        run: |
          if grep -RniE "(storybook|tailwind)" --exclude-dir=node_modules --exclude="*.lock" -- .; then
            echo "Banned tool reference found"; exit 1;
          fi

      - name: Lint (Biome)
        run: bun run lint

      - name: Markdownlint
        run: bun run mdlint

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build
